# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: p2p.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'p2p.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tp2p.proto\x12\x03p2p\"A\n\tFileChunk\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x14\n\x0c\x63hunk_number\x18\x03 \x01(\x05\"5\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x14\n\x0c\x63hunk_number\x18\x02 \x01(\x05\"!\n\x0eUploadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"*\n\x08PeerInfo\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\r\n\x05\x66iles\x18\x02 \x03(\t\"#\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x19\n\x08PeerList\x12\r\n\x05peers\x18\x01 \x03(\t2s\n\nP2PService\x12\x31\n\nUploadFile\x12\x0e.p2p.FileChunk\x1a\x13.p2p.UploadResponse\x12\x32\n\x0c\x44ownloadFile\x12\x10.p2p.FileRequest\x1a\x0e.p2p.FileChunk0\x01\x32u\n\x0eTrackerService\x12\x34\n\x0cRegisterPeer\x12\r.p2p.PeerInfo\x1a\x15.p2p.RegisterResponse\x12-\n\nQueryPeers\x12\x10.p2p.FileRequest\x1a\r.p2p.PeerListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'p2p_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILECHUNK']._serialized_start=18
  _globals['_FILECHUNK']._serialized_end=83
  _globals['_FILEREQUEST']._serialized_start=85
  _globals['_FILEREQUEST']._serialized_end=138
  _globals['_UPLOADRESPONSE']._serialized_start=140
  _globals['_UPLOADRESPONSE']._serialized_end=173
  _globals['_PEERINFO']._serialized_start=175
  _globals['_PEERINFO']._serialized_end=217
  _globals['_REGISTERRESPONSE']._serialized_start=219
  _globals['_REGISTERRESPONSE']._serialized_end=254
  _globals['_PEERLIST']._serialized_start=256
  _globals['_PEERLIST']._serialized_end=281
  _globals['_P2PSERVICE']._serialized_start=283
  _globals['_P2PSERVICE']._serialized_end=398
  _globals['_TRACKERSERVICE']._serialized_start=400
  _globals['_TRACKERSERVICE']._serialized_end=517
# @@protoc_insertion_point(module_scope)
